# Generated by Django 5.0.6 on 2026-06-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intro',
            name='hobby',
            field=models.TextField(blank=True),
        ),
    ]
